/*
 * Listenarr - Audiobook Management System
 * Copyright (C) 2024-2026 Listenarr Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */
// <auto-generated />
using System;
using Listenarr.Infrastructure.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Listenarr.Infrastructure.Migrations
{
    [DbContext(typeof(ListenArrDbContext))]
    [Migration("20260211185500_AddDownloadErrorTrackingFields")]
    partial class AddDownloadErrorTrackingFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            // This file is auto-generated and will be updated when migrations are scaffolded
            // The key changes in this migration:
            // - Added ImportBlockReason (string, nullable) to Downloads
            // - Added ImportBlockMessages (string, nullable) to Downloads (stored as JSON)
            // - Added ImportAttempts (int) to Downloads
            // - Added LastImportedAt (DateTime, nullable) to Downloads
            // - Added HistoryId (int, nullable) to Downloads

            // Full entity definitions would be generated by EF Core
            // This is a placeholder that will be replaced when scaffolding updates it
        }
    }
}
