// <auto-generated />
using System;
using Listenarr.Infrastructure.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Listenarr.Infrastructure.Migrations
{
    [DbContext(typeof(ListenArrDbContext))]
    [Migration("20260211185500_AddDownloadErrorTrackingFields")]
    partial class AddDownloadErrorTrackingFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            // This file is auto-generated and will be updated when migrations are scaffolded
            // The key changes in this migration:
            // - Added ImportBlockReason (string, nullable) to Downloads
            // - Added ImportBlockMessages (string, nullable) to Downloads (stored as JSON)
            // - Added ImportAttempts (int) to Downloads
            // - Added LastImportedAt (DateTime, nullable) to Downloads
            // - Added HistoryId (int, nullable) to Downloads

            // Full entity definitions would be generated by EF Core
            // This is a placeholder that will be replaced when scaffolding updates it
        }
    }
}
