<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <DefaultItemExcludes>$(DefaultItemExcludes);artifacts\**;.tmp\**;obj2\**</DefaultItemExcludes>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Models\**\*.cs" />
  </ItemGroup>
</Project>
