// <auto-generated />
using Listenarr.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Listenarr.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ListenArrDbContext))]
    [Migration("20260818132300_AddFileMutationParentGenerationProofs")]
    partial class AddFileMutationParentGenerationProofs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            AddMoveJobRelocationForeignKey.BuildHistoricalModel(modelBuilder);

            modelBuilder.Entity("Listenarr.Domain.Downloads.FileMutationJournal", b =>
                {
                    b.Property<string>("DestinationParentDirectoryObjectIdentity")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceParentDirectoryObjectIdentity")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");
                });
#pragma warning restore 612, 618
        }
    }
}
