<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\listenarr.domain\Listenarr.Domain.csproj" />
    <ProjectReference Include="..\listenarr.application\Listenarr.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="SharpCompress" />
    <PackageReference Include="HtmlAgilityPack" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" />
    <PackageReference Include="Polly" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Listenarr.Tests" />
  </ItemGroup>

</Project>
