<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\listenarr.domain\Listenarr.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite.Core" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="HtmlAgilityPack" />
    <PackageReference Include="AsyncKeyedLock" />
    <PackageReference Include="TagLibSharp" />
    <PackageReference Include="SixLabors.ImageSharp" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Listenarr.Tests" />
  </ItemGroup>

</Project>
