<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\listenarr.domain\Listenarr.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AsyncKeyedLock" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Listenarr.Tests" />
  </ItemGroup>

</Project>
