<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <EFVersion>8.*</EFVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\listenarr.domain\Listenarr.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="$(EFVersion)" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="$(EFVersion)" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="$(EFVersion)" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
